services:
  app:
    build: .
    restart: always
    ports:
      - 3001:8000
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./media:/app/media
    devices:
        - /dev/dri/renderD128:/dev/dri/renderD128
    depends_on:
      - db
      - redis
  db:
    image: mariadb:latest
    restart: always
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pyrec
      MYSQL_USER: pyrec
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    environment:
      TZ: 'Asia/Tokyo'
  celery-worker:
    build: .
    command: bash -c "celery -A pyrec worker -l info"
    restart: always
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./media:/app/media
      - ./encode-scripts/:/app/record/encode/
    devices:
        - /dev/dri/renderD128:/dev/dri/renderD128
    depends_on:
      - db
      - redis
    init : true
  celery-beat:
    build: .
    command: celery -A pyrec beat -l info
    restart: always
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - db
      - redis
