# Generated by Django 5.0.7 on 2024-08-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guide", "0006_relateditem_unique_related_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(blank=True, max_length=255, null=True)),
                ("service_id", models.IntegerField(blank=True, null=True)),
                ("is_enable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recorded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="recorded/")),
                ("started_at", models.DateTimeField()),
                ("last_updated_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_recording", models.BooleanField(default=False)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="guide.program"
                    ),
                ),
            ],
        ),
    ]
