# Generated by Django 5.0.7 on 2024-08-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordrule",
            name="recording_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
