# Generated by Django 5.0.7 on 2024-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0004_alter_encodetask_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordrule",
            name="encoder_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="encodetask",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
