# Generated by Django 5.0.7 on 2024-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0006_recordrule_encoding_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="encodetask",
            name="encoding_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="encodetask",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
