# Generated by Django 5.0.7 on 2024-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="audio_infos",
            field=models.ManyToManyField(blank=True, null=True, to="guide.audioinfo"),
        ),
        migrations.AlterField(
            model_name="program",
            name="genres",
            field=models.ManyToManyField(blank=True, null=True, to="guide.genre"),
        ),
        migrations.AlterField(
            model_name="program",
            name="related_items",
            field=models.ManyToManyField(blank=True, null=True, to="guide.relateditem"),
        ),
    ]
