# Generated by Django 5.0.7 on 2024-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0002_alter_program_audio_infos_alter_program_genres_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relateditem",
            name="event_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="relateditem",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("shared", "Shared"),
                    ("relay", "Relay"),
                    ("movement", "Movement"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="relateditem",
            name="network_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="relateditem",
            name="service_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
