# Generated by Django 5.0.7 on 2024-08-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0006_relateditem_unique_related_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="audio_infos",
        ),
        migrations.RemoveField(
            model_name="program",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="program",
            name="related_items",
        ),
        migrations.AlterField(
            model_name="program",
            name="video_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AudioInfo",
        ),
        migrations.AddField(
            model_name="program",
            name="audio_infos",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.AddField(
            model_name="program",
            name="genres",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="RelatedItem",
        ),
        migrations.AddField(
            model_name="program",
            name="related_items",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="VideoInfo",
        ),
    ]
