# Generated by Django 5.0.7 on 2024-08-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0007_remove_program_audio_infos_remove_program_genres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
